### ISSUE TITLE
backdrop-filter blur

### ISSUE THREAD

**Issue by gsdev01** [pixijs/pixi-picture#16]
Hi,

First things first, thanks for your amazing work on PixiJS.

I'm struggling to create a backdrop-filter blur like this one done in CSS : [https://codepen.io/gesteves/pen/PwRPZa](url)
The main idea is to have a blurred Graphics above other "layers" (zIndex) of contents (sprites, graphics...)

Any clue achieving this ? 

Thanks in advance.

**Comment by ivanpopelyshev** [comment]
Yes, its possible, i just didnt make that demo yet. Thanks for reminding me :)

I want to make a simple filter that can accept any other filter and make it backdrop. In theory, considering what I already have in pixi-picture - its easy. But i didnt have time to try it yet

**Comment by gsdev01** [comment]
Thanks for you fast reply.

Any clue achieving this by my own ? 

thanks

**Comment by ivanpopelyshev** [comment]
Im debugging it at the moment

**Comment by ivanpopelyshev** [comment]
Done. npm 2.0.1, or `dist` in this repo.

https://pixijs.io/examples/#/plugin-picture/mask-blur.js

**Comment by ivanpopelyshev** [comment]
wait, something is wrong in easy version of window

**Comment by ivanpopelyshev** [comment]
OK, try again. If it doesnt work, ctrl+f5 this file and reopen examples: https://pixijs.io/examples/pixi-plugins/pixi-picture.js

**Comment by ivanpopelyshev** [comment]
I see one strange artifact in "easy" window, at the bottom of it.

**Comment by ivanpopelyshev** [comment]
OK, fixed again. Same procedure regarding browser cache.

**Comment by gsdev01** [comment]
thank you so much for your work ! This is exactly what I was lookin' for !
