### ISSUE TITLE
 glCopyTexSubImage2D: incompatible format

### ISSUE THREAD

**Issue by weepy** [pixijs/pixi-picture#3]
Running the example in both Chrome and Safari I get the following error 

GL ERROR :GL_INVALID_OPERATION : glCopyTexSubImage2D: incompatible format

It seems to be coming from this line: gl.copyTexSubImage2D(gl.TEXTURE_2D, 0, 0, 0, x_1, y_1, pixelsWidth, pixelsHeight);

Removing the stage.filters the problem goes away, but I'm guessing that the VoidFilter speed up isn't working in either case.

**Comment by ivanpopelyshev** [comment]
right, i think i found what was wrong in v4 and v5. we can close it.
