### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by Teoxoy** [pixijs/pixi-picture#9]
Add a description, something like this: A plugin that includes a sprite renderer that reduces border artifacts and 3 blend mode implementations for WebGL

**Comment by Teoxoy** [comment]
Some topics would also be nice :)

**Comment by ivanpopelyshev** [comment]
That's the problem - somehow, I lost permissions to this repo. When I take them back, I'll change description, good idea!

**Comment by Teoxoy** [comment]
Oh, ok
